language: generic

env:
  global:
    - ENCRYPTION_LABEL="e149beb9c312"
    - DEPLOY_USER="annevankesteren"
script:
  - curl --verbose --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh
notifications:
  email:
    on_success: never
    on_failure: always
